import type { OrdemServicoDetalhe, ServicoDetalhe, TarefaDetalhe } from './services';
import type { UsuarioApi } from '@/features/usuarios/services';

// ID da usuária "Daniele Menezes" no mock — usada para o badge "VOCÊ" e filtro "Minhas tarefas"
export const MOCK_CURRENT_USER_ID = 6;

export const MOCK_ORDEM: OrdemServicoDetalhe = {
  id: 2041,
  cliente: 1,
  cliente_detail: {
    id: 1,
    nome: 'Northwind Tecnologia Ltda',
    tipo_inscricao: 'cnpj',
    numero_inscricao: '23.456.789/0001-01',
    telefone_institucional: '(21) 3456-7890',
    email_institucional: 'contato@northwind.com.br',
    ativo: true,
  },
  criado_por: 1,
  criado_por_nome: 'Analine Souza',
  data_criacao: '2026-06-24',
  criada_em: '2026-06-24T09:00:00Z',
  status: 'em_andamento',
  status_display: 'Em andamento',
  prioridade: 'media',
  prioridade_display: 'Média',
  valor: '18400.00',
  forma_pagamento: 'boleto',
  forma_pagamento_display: 'Boleto',
  quantidade_parcelas: 3,
  cobranca_imediata: false,
  nome_contato_envio_nf: 'Felipe Andrade',
  contato_envio_nf: 'financeiro@northwind.com.br',
  contrato: true,
  objeto_contrato: 'Desenvolvimento de plataforma integrada de gestão e e-commerce B2B',
  contrato_data_inicio: '2026-01-01',
  contrato_data_fim: '2026-12-31',
  gestor_contrato_nome: 'Patricia Lima',
  gestor_contrato_email: 'patricia@northwind.com.br',
  gestor_contrato_telefone: '(21) 99876-5432',
  observacao: 'Cliente estratégico — prioridade máxima em atendimento e entrega.',
  concluida: false,
  faturada: false,
  numero_nf: null,
  data_faturamento: null,
  faturada_por: null,
  faturada_por_nome: null,
  liberada_para_faturamento: false,
  liberada_para_faturamento_em: null,
  liberada_para_faturamento_por: null,
  liberada_para_faturamento_por_nome: null,
  data_atualizacao: '2026-06-29T10:00:00Z',
  atualizado_por: 2,
  data_conclusao_os: null,
  finalizador_nome: null,
};

export const MOCK_SERVICOS: ServicoDetalhe[] = [
  {
    id: 1,
    ordem_servico: 2041,
    repositorio: 1,
    repositorio_detail: { id: 1, nome: 'Módulo de Pagamentos', descricao: null },
    repositorio_nome: 'Módulo de Pagamentos',
    descricao:
      'Implementação do fluxo completo de pagamento online: checkout, integração com gateway, confirmação via webhook e tratamento de reembolsos. Escopo aprovado pelo cliente na reunião de kickoff de 24/06.',
    status: 'em_andamento',
    status_display: 'Em andamento',
    data_inicio: '2026-06-24',
    data_termino: null,
    data_conclusao: null,
    terminado_por: null,
    terminado_por_nome: null,
    criado_em: '2026-06-24T09:00:00Z',
    atualizado_em: '2026-06-29T10:00:00Z',
  },
  {
    id: 2,
    ordem_servico: 2041,
    repositorio: 2,
    repositorio_detail: { id: 2, nome: 'Painel Administrativo', descricao: null },
    repositorio_nome: 'Painel Administrativo',
    descricao:
      'Construção do painel interno de administração: listagem e gestão de usuários, filtros avançados de busca e exportação de relatórios operacionais em CSV.',
    status: 'aberto',
    status_display: 'Aberto',
    data_inicio: '2026-06-26',
    data_termino: null,
    data_conclusao: null,
    terminado_por: null,
    terminado_por_nome: null,
    criado_em: '2026-06-24T09:00:00Z',
    atualizado_em: '2026-06-29T10:00:00Z',
  },
  {
    id: 3,
    ordem_servico: 2041,
    repositorio: 3,
    repositorio_detail: { id: 3, nome: 'Notificações & E-mail', descricao: null },
    repositorio_nome: 'Notificações & E-mail',
    descricao:
      'Camada de notificações transacionais por e-mail: templates, fila de envio assíncrona e registro de entregas com retentativa automática.',
    status: 'concluida',
    status_display: 'Concluída',
    data_inicio: '2026-06-12',
    data_termino: '2026-06-23',
    data_conclusao: '2026-06-23',
    terminado_por: 4,
    terminado_por_nome: 'Bruno Costa',
    criado_em: '2026-06-12T09:00:00Z',
    atualizado_em: '2026-06-23T17:00:00Z',
  },
  {
    id: 4,
    ordem_servico: 2041,
    repositorio: 4,
    repositorio_detail: { id: 4, nome: 'Integração ERP', descricao: null },
    repositorio_nome: 'Integração ERP',
    descricao:
      'Sincronização bidirecional de produtos, estoque e pedidos com o ERP do cliente via API REST. Aguardando liberação das credenciais de acesso.',
    status: 'aberto',
    status_display: 'Aberto',
    data_inicio: null,
    data_termino: null,
    data_conclusao: null,
    terminado_por: null,
    terminado_por_nome: null,
    criado_em: '2026-06-24T09:00:00Z',
    atualizado_em: '2026-06-24T09:00:00Z',
  },
];

export const MOCK_TAREFAS: Record<number, TarefaDetalhe[]> = {
  // Módulo de Pagamentos — em_andamento
  1: [
    {
      id: 1,
      servico: 1,
      responsavel: 2,
      responsavel_nome: 'Marina Alves',
      cliente_nome: 'Northwind Tecnologia Ltda',
      repositorio_nome: 'Módulo de Pagamentos',
      descricao: 'Implementar endpoint de checkout com validação de cartão, cálculo de frete e geração de pedido.',
      status: 'em_andamento',
      status_display: 'Em andamento',
      data_inicio: '2026-06-24',
      data_termino: null,
      criada_em: '2026-06-24T09:00:00Z',
      atualizado_em: '2026-06-29T10:00:00Z',
    },
    {
      id: 2,
      servico: 1,
      responsavel: 3,
      responsavel_nome: 'Carlos Paiva',
      cliente_nome: 'Northwind Tecnologia Ltda',
      repositorio_nome: 'Módulo de Pagamentos',
      descricao: 'Testar integração com o gateway em ambiente sandbox e mapear todos os códigos de retorno de erro.',
      status: 'aberta',
      status_display: 'Aberta',
      data_inicio: '2026-06-25',
      data_termino: null,
      criada_em: '2026-06-24T09:00:00Z',
      atualizado_em: '2026-06-24T09:00:00Z',
    },
    {
      id: 3,
      servico: 1,
      responsavel: MOCK_CURRENT_USER_ID,
      responsavel_nome: 'Daniele Menezes',
      cliente_nome: 'Northwind Tecnologia Ltda',
      repositorio_nome: 'Módulo de Pagamentos',
      descricao: 'Configurar webhooks de confirmação de pagamento garantindo idempotência dos eventos recebidos.',
      status: 'aberta',
      status_display: 'Aberta',
      data_inicio: null,
      data_termino: null,
      criada_em: '2026-06-24T09:00:00Z',
      atualizado_em: '2026-06-24T09:00:00Z',
    },
    {
      id: 4,
      servico: 1,
      responsavel: 2,
      responsavel_nome: 'Marina Alves',
      cliente_nome: 'Northwind Tecnologia Ltda',
      repositorio_nome: 'Módulo de Pagamentos',
      descricao: 'Documentar o fluxo de reembolso parcial e total na base de conhecimento do time.',
      status: 'concluida',
      status_display: 'Concluída',
      data_inicio: '2026-06-20',
      data_termino: '2026-06-23',
      criada_em: '2026-06-20T09:00:00Z',
      atualizado_em: '2026-06-23T17:00:00Z',
    },
  ],

  // Painel Administrativo — aberto
  2: [
    {
      id: 5,
      servico: 2,
      responsavel: MOCK_CURRENT_USER_ID,
      responsavel_nome: 'Daniele Menezes',
      cliente_nome: 'Northwind Tecnologia Ltda',
      repositorio_nome: 'Painel Administrativo',
      descricao: 'Montar a tela de listagem de usuários com paginação, ordenação por coluna e ações em massa.',
      status: 'em_andamento',
      status_display: 'Em andamento',
      data_inicio: '2026-06-26',
      data_termino: null,
      criada_em: '2026-06-26T09:00:00Z',
      atualizado_em: '2026-06-29T10:00:00Z',
    },
    {
      id: 6,
      servico: 2,
      responsavel: 5,
      responsavel_nome: 'Rafael Lima',
      cliente_nome: 'Northwind Tecnologia Ltda',
      repositorio_nome: 'Painel Administrativo',
      descricao: 'Implementar filtros e busca avançada por nome, perfil e status de acesso.',
      status: 'aberta',
      status_display: 'Aberta',
      data_inicio: null,
      data_termino: null,
      criada_em: '2026-06-26T09:00:00Z',
      atualizado_em: '2026-06-26T09:00:00Z',
    },
    {
      id: 7,
      servico: 2,
      responsavel: 2,
      responsavel_nome: 'Marina Alves',
      cliente_nome: 'Northwind Tecnologia Ltda',
      repositorio_nome: 'Painel Administrativo',
      descricao: 'Exportação CSV de relatórios — cancelada: substituída pelo módulo de BI já existente.',
      status: 'cancelada',
      status_display: 'Cancelada',
      data_inicio: null,
      data_termino: null,
      criada_em: '2026-06-26T09:00:00Z',
      atualizado_em: '2026-06-28T14:00:00Z',
    },
  ],

  // Notificações & E-mail — concluída
  3: [
    {
      id: 8,
      servico: 3,
      responsavel: 4,
      responsavel_nome: 'Bruno Costa',
      cliente_nome: 'Northwind Tecnologia Ltda',
      repositorio_nome: 'Notificações & E-mail',
      descricao: 'Criar templates responsivos de e-mail para confirmação, recuperação de senha e alertas.',
      status: 'concluida',
      status_display: 'Concluída',
      data_inicio: '2026-06-12',
      data_termino: '2026-06-18',
      criada_em: '2026-06-12T09:00:00Z',
      atualizado_em: '2026-06-18T17:00:00Z',
    },
    {
      id: 9,
      servico: 3,
      responsavel: 3,
      responsavel_nome: 'Carlos Paiva',
      cliente_nome: 'Northwind Tecnologia Ltda',
      repositorio_nome: 'Notificações & E-mail',
      descricao: 'Implementar fila assíncrona de envio com retentativa exponencial em caso de falha.',
      status: 'concluida',
      status_display: 'Concluída',
      data_inicio: '2026-06-15',
      data_termino: '2026-06-21',
      criada_em: '2026-06-12T09:00:00Z',
      atualizado_em: '2026-06-21T17:00:00Z',
    },
    {
      id: 10,
      servico: 3,
      responsavel: 4,
      responsavel_nome: 'Bruno Costa',
      cliente_nome: 'Northwind Tecnologia Ltda',
      repositorio_nome: 'Notificações & E-mail',
      descricao: 'Registrar entregas, aberturas e bounces em painel de monitoramento.',
      status: 'concluida',
      status_display: 'Concluída',
      data_inicio: '2026-06-20',
      data_termino: '2026-06-23',
      criada_em: '2026-06-20T09:00:00Z',
      atualizado_em: '2026-06-23T17:00:00Z',
    },
  ],

  // Integração ERP — aberto, sem tarefas
  4: [],
};

export const MOCK_USUARIOS: UsuarioApi[] = [
  {
    id: 2,
    email: 'marina.alves@ergogroup.com.br',
    username: 'marina.alves',
    nome_completo: 'Marina Alves',
    tipo_usuario: 'tecnico',
    tipo_usuario_display: 'Técnico',
    ativo: true,
    is_staff: false,
    is_superuser: false,
  },
  {
    id: 3,
    email: 'carlos.paiva@ergogroup.com.br',
    username: 'carlos.paiva',
    nome_completo: 'Carlos Paiva',
    tipo_usuario: 'tecnico',
    tipo_usuario_display: 'Técnico',
    ativo: true,
    is_staff: false,
    is_superuser: false,
  },
  {
    id: 4,
    email: 'bruno.costa@ergogroup.com.br',
    username: 'bruno.costa',
    nome_completo: 'Bruno Costa',
    tipo_usuario: 'tecnico',
    tipo_usuario_display: 'Técnico',
    ativo: true,
    is_staff: false,
    is_superuser: false,
  },
  {
    id: 5,
    email: 'rafael.lima@ergogroup.com.br',
    username: 'rafael.lima',
    nome_completo: 'Rafael Lima',
    tipo_usuario: 'tecnico',
    tipo_usuario_display: 'Técnico',
    ativo: true,
    is_staff: false,
    is_superuser: false,
  },
  {
    id: MOCK_CURRENT_USER_ID,
    email: 'daniele.menezes@ergogroup.com.br',
    username: 'daniele.menezes',
    nome_completo: 'Daniele Menezes',
    tipo_usuario: 'tecnico',
    tipo_usuario_display: 'Técnico',
    ativo: true,
    is_staff: false,
    is_superuser: false,
  },
];
